baseurl = "https://sidewinder12s.github.io/"
languageCode = "en-us"
title = "Geoff Webster"
MetaDataFormat = "toml"
theme = "redlounge"
#paginate =  10
watch = true
pygmentsstyle="solarizeddark"

[author]
  name = "Geoff Webster"

[params]
  sidebartitle = "Geoff Webster"
  sidebartagline = "To the Cloud!"
[menus]
[[menu.main]]
  name = "Blog"
  url = "/posts"
[[menu.main]]
  name = "About"
  url = "about.html"
[[menu.main]]
  name = "Resume"
  url = "Resume.html"
[[menu.social]]
  pre = "<i class='fa fa-github'></i>"
  url = "https://www.github.com/sidewinder12s"
  identifier = "GitHub"
[[menu.social]]
  pre = "<i class='fa fa-linkedin'></i>"
  url = "https://www.linkedin.com/in/geoffwebster"
  identifier = "LinkedIn"
[[menu.social]]
  pre = "<i class='fa fa-envelope'></i>"
  url = "geoffowebster@gmail.com"
  identifier = "Email"
[[permalinks]]
  post = "/:year/:month/:day/:title"
#[[menu.social]]
 #pre = "<i class='fa fa-github'></i>"
  #url = "https://www.github.com/sidewinder12s"
  #identifier = "GitHub"

[taxonomies]
   tag = "tags"
   category = "categories"